conky.config = {
    alignment = 'top_right',

    gap_x = 20,
    gap_y = 300,

    background = true,
    double_buffer = true,

    own_window = true,
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,

    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    use_xft = true,
    font = 'Hack:size=13',

    draw_shades = true,
    default_shade_color = '000000',

    uppercase = false,
    update_interval = 1.0,

    minimum_width = 600,
    minimum_height = 400,
};

conky.text = [[
${execpi 2 ./app.py --conky}
]];
